# Generated by Django 6.0.5 on 2026-05-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Слово (маленькими буквами)')),
                ('stress_index', models.IntegerField(verbose_name='Индекс правильной буквы(с нуля)')),
            ],
        ),
    ]
